[general]
output = "/exp/icarus/data/users/jkoh1/1u1p_example"
primfn = "default_primary_classification"
pidfn = "default_pid"
fsthresh = [
    "@photon_threshold",
    "@electron_threshold",
    "@muon_threshold",
    "@pion_threshold",
    "@proton_threshold",
]

[parameters]
photon_threshold = 25.0
electron_threshold = 25.0
muon_threshold = 143.425
pion_threshold = 25.0
proton_threshold = 50.0

[[category]] # 0 : Neutrino, charged current
cuts = [
    { name = "neutrino" },
    { name = "iscc"     },
]

[[category]] # 1 : Neutrino, neutral current
cuts = [
    { name = "neutrino" },
    { name = "!iscc"    },
]

[[category]] # 2 : Cosmic
cuts = [
    { name = "!neutrino" },
]

[[sample]]
name = "simulation"
path = "/exp/icarus/data/users/jkoh1/NuMI_CV_flat_cafs_2_00.root"
ismc = true

[[tree]]
name = "selected"
sim_only = false
mode = "reco"
cut = [
    { name = "fiducial_cut",     type = "reco" },
    { name = "containment_cut",  type = "reco" },
    { name = "valid_flashmatch", type = "reco" },
    { name = "no_photons",       type = "reco", parameters = [ "@photon_threshold"   ] },
    { name = "no_electrons",     type = "reco", parameters = [ "@electron_threshold" ] },
    { name = "no_charged_pions", type = "reco", parameters = [ "@pion_threshold"     ] },
    { name = "single_muon",      type = "reco", parameters = [ "@muon_threshold"     ] },
    { name = "single_proton",    type = "reco", parameters = [ "@proton_threshold"   ] },
]
branch = [
    { name = "neutrino_id",      type = "true"},
    { name = "baseline",         type = "mctruth"},
    { name = "cc",               type = "mctruth"},
    { name = "pdg",              type = "mctruth"},
    { name = "interaction_type", type = "mctruth"},
    { name = "category",         type = "true"},
    { name = "neutrino_energy",  type = "mctruth"},
    { name = "visible_energy",   type = "both"},
    { name = "dpT",              type = "both"},
    { name = "flash_time",       type = "reco"}
]

[[tree]]
name = "signal"
sim_only = true
mode = "true"
cut = [
    { name = "neutrino",         type = "true" },
    { name = "fiducial_cut",     type = "true" },
    { name = "containment_cut",  type = "true" },
    { name = "no_photons",       type = "true", parameters = [ "@photon_threshold"   ] },
    { name = "no_electrons",     type = "true", parameters = [ "@electron_threshold" ] },
    { name = "no_charged_pions", type = "true", parameters = [ "@pion_threshold"     ] },
    { name = "single_muon",      type = "true", parameters = [ "@muon_threshold"     ] },
    { name = "single_proton",    type = "true", parameters = [ "@proton_threshold"   ] },
]
branch = [
    {name = "neutrino_id",           type = "true"},
    {name = "category",              type = "true"},
    {name = "visible_energy",        type = "both"},
    {name = "fiducial",              type = "reco"},
    {name = "containment",           type = "reco"},
    {name = "flash_time",            type = "reco"},
    {name = "photon_multiplicity",   type = "reco", parameters = [ "@photon_threshold"   ]},
    {name = "electron_multiplicity", type = "reco", parameters = [ "@electron_threshold" ]},
    {name = "muon_multiplicity",     type = "reco", parameters = [ "@muon_threshold"     ]},
    {name = "pion_multiplicity",     type = "reco", parameters = [ "@pion_threshold"     ]},
    {name = "proton_multiplicity",   type = "reco", parameters = [ "@proton_threshold"   ]},
    
]