[general]
output = "/exp/icarus/data/users/jkoh1/All_NuMI_BNB_2_shower_event_preselection_analysis"
primfn = "default_primary_classification"
pidfn = "default_pid"
fsthresh = [
    "@photon_threshold",
    "@electron_threshold",
    "@muon_threshold",
    "@pion_threshold",
    "@proton_threshold",
]

[parameters]
photon_threshold = 25.0
electron_threshold = 25.0
muon_threshold = 143.425
pion_threshold = 25.0
proton_threshold = 50.0

#NuMI Samples

[[sample]]
name = "NuMI_simulation"
path = "/pnfs/icarus/persistent/users/dcarber/spine/combined_files/NuMI_CV_flat_cafs_2/*.root"
ismc = true
disable = false

#BNB samples

[[sample]]
name = "BNB_simulation"
path = "/pnfs/icarus/persistent/users/mueller/production/simulation/nominal/input*.flat.root"
ismc = true
disable = false

#Pre-selection efficiency analysis -----------------------------------------------------------------------------

#interaction level ------------------------------------------------------------------------------

#Pre-selection no cut ---------------------------------------------------------

[[tree]] # reco no cuts  
name = "interaction_nocut_reco"
sim_only = false
mode = "reco"
cut = [
    { name = "no_cut",          type = "reco" },
]
branch = [
    #Multiplicity tests and interaction level
    {name = "fiducial_cut",          type = "both"    },
    {name = "containment_cut",       type = "both"    },
    {name = "valid_flashmatch",      type = "both"    },
    {name = "neutrino",              type = "true"    },
]


[[tree]] # true no cuts  
name = "interaction_nocut_true"
sim_only = true
mode = "true"
cut = [
    { name = "no_cut",          type = "true" },
]
branch = [
    #Multiplicity tests and interaction level
    {name = "fiducial_cut",          type = "both"    },
    {name = "containment_cut",       type = "both"    },
    {name = "valid_flashmatch",      type = "both"    },
    {name = "neutrino",              type = "true"    },
]

#Pre-selection neutrino cut ---------------------------------------------------------

[[tree]] # reco neutrino cut
name = "interaction_trueneutrino_cut_reco"
sim_only = false
mode = "reco"
cut = [
    {name = "neutrino",              type = "true"    },
]
branch = [
    #Multiplicity tests and interaction level
    {name = "fiducial_cut",          type = "both"    },
    {name = "containment_cut",       type = "both"    },
    {name = "valid_flashmatch",      type = "both"    },
    {name = "neutrino",              type = "true"    },
]

[[tree]] # reco valid_flashmatch cut
name = "interaction_flashmatch_cut_reco"
sim_only = false
mode = "reco"
cut = [
    {name = "valid_flashmatch",      type = "reco"    },
]
branch = [
    #Multiplicity tests and interaction level
    {name = "fiducial_cut",          type = "both"    },
    {name = "containment_cut",       type = "both"    },
    {name = "valid_flashmatch",      type = "both"    },
    {name = "neutrino",              type = "true"    },
]

[[tree]] # true neutrino cut  
name = "interaction_neutrino_cut_true"
sim_only = true
mode = "true"
cut = [
    {name = "neutrino",              type = "true"    },
]
branch = [
    #Multiplicity tests and interaction level
    {name = "fiducial_cut",          type = "both"    },
    {name = "containment_cut",       type = "both"    },
    {name = "valid_flashmatch",      type = "both"    },
    {name = "neutrino",              type = "true"    },
]

#pre-selection cuts---------------------------------------------------------------------------------------

[[tree]] # reco preselection
name = "interaction_fiducial_containtment_flashmatch_cut_reco"
sim_only = false
mode = "reco"
cut = [
    { name = "fiducial_cut",          type = "reco" },
    { name = "containment_cut",       type = "reco" },
    { name = "valid_flashmatch",      type = "reco" },
    ]
branch = [
    #Multiplicity tests and interaction level
    {name = "photon_multiplicity",   type = "both", parameters = [ "@photon_threshold"   ]},
    {name = "electron_multiplicity", type = "both", parameters = [ "@electron_threshold" ]},
    {name = "muon_multiplicity",     type = "both", parameters = [ "@muon_threshold"     ]},
    {name = "pion_multiplicity",     type = "both", parameters = [ "@pion_threshold"     ]},
    {name = "proton_multiplicity",   type = "both", parameters = [ "@proton_threshold"   ]},
    {name = "fiducial_cut",          type = "both"                                        },
    {name = "containment_cut",       type = "both"                                        },
    {name = "valid_flashmatch",      type = "both"                                        },
    {name = "neutrino",              type = "true"                                        },
]

[[tree]] # reco preselection
name = "interaction_fiducial_flashmatch_cut_reco"
sim_only = false
mode = "reco"
cut = [
    { name = "fiducial_cut",          type = "reco" },
    { name = "valid_flashmatch",      type = "reco" },
    ]
branch = [
    #Multiplicity tests and interaction level
    {name = "photon_multiplicity",   type = "both", parameters = [ "@photon_threshold"   ]},
    {name = "electron_multiplicity", type = "both", parameters = [ "@electron_threshold" ]},
    {name = "muon_multiplicity",     type = "both", parameters = [ "@muon_threshold"     ]},
    {name = "pion_multiplicity",     type = "both", parameters = [ "@pion_threshold"     ]},
    {name = "proton_multiplicity",   type = "both", parameters = [ "@proton_threshold"   ]},
    {name = "fiducial_cut",          type = "both"    },
    {name = "containment_cut",       type = "both"    },
    {name = "valid_flashmatch",      type = "both"    },
    {name = "neutrino",              type = "true"    },
]

[[tree]] # true preselection
name = "interaction_fiducial_containment_neutrino_cut_true"
sim_only = false
mode = "reco"
cut = [
    { name = "fiducial_cut",          type = "true" },
    { name = "containment_cut",       type = "true" },
    { name = "neutrino",              type = "true" },
    ]
branch = [
    #Multiplicity tests and interaction level
    {name = "photon_multiplicity",   type = "both", parameters = [ "@photon_threshold"   ]},
    {name = "electron_multiplicity", type = "both", parameters = [ "@electron_threshold" ]},
    {name = "muon_multiplicity",     type = "both", parameters = [ "@muon_threshold"     ]},
    {name = "pion_multiplicity",     type = "both", parameters = [ "@pion_threshold"     ]},
    {name = "proton_multiplicity",   type = "both", parameters = [ "@proton_threshold"   ]},
    {name = "fiducial_cut",          type = "both"    },
    {name = "containment_cut",       type = "both"    },
    {name = "valid_flashmatch",      type = "both"    },
    {name = "neutrino",              type = "true"    },
]


[[tree]] # true preselection
name = "interaction_fiducial_neutrino_cut_true"
sim_only = false
mode = "reco"
cut = [
    { name = "fiducial_cut",          type = "true" },
    { name = "neutrino",              type = "true" },
    ]
branch = [
    #Multiplicity tests and interaction level
    {name = "photon_multiplicity",   type = "both", parameters = [ "@photon_threshold"   ]},
    {name = "electron_multiplicity", type = "both", parameters = [ "@electron_threshold" ]},
    {name = "muon_multiplicity",     type = "both", parameters = [ "@muon_threshold"     ]},
    {name = "pion_multiplicity",     type = "both", parameters = [ "@pion_threshold"     ]},
    {name = "proton_multiplicity",   type = "both", parameters = [ "@proton_threshold"   ]},
    {name = "fiducial_cut",          type = "both"    },
    {name = "containment_cut",       type = "both"    },
    {name = "valid_flashmatch",      type = "both"    },
    {name = "neutrino",              type = "true"    },
]

#Particle level ------------------------------------------------------------------------------

#Pre-selection no cut ---------------------------------------------------------

[[tree]] # reco no cuts  
name = "particle_nocut_reco"
sim_only = false
mode = "reco"
cut = [
    { name = "no_cut",          type = "reco" },
]
branch = [
    #Multiplicity tests and interaction level
    {name = "containment_cut",       type = "both_particle"    },
]

[[tree]] # true no cuts  
name = "particle_nocut_true"
sim_only = true
mode = "true"
cut = [
    { name = "no_cut",          type = "true" },
]
branch = [
    #Multiplicity tests and interaction level
    {name = "containment_cut",       type = "both_particle"    },
]

#Pre-selection cuts ---------------------------------------------------------

[[tree]] # reco preselection
name = "particle_intfiducial_cut_reco"
sim_only = false
mode = "reco"
cut = [
    { name = "fiducial_cut",          type = "reco" },
    ]
branch = [
    #Multiplicity tests and interaction level
    {name = "containment_cut",       type = "both_particle"                               },
    {name = "primary_classification",type = "both_particle"                               },
    {name = "pid",                   type = "both_particle"                               },
    {name = "semantic_type",         type = "both_particle"                               },
]

[[tree]] # reco preselection
name = "particle_intfiducial_intflashmatch_cut_reco"
sim_only = false
mode = "reco"
cut = [
    { name = "fiducial_cut",          type = "reco" },
    { name = "valid_flashmatch",      type = "reco" },
    ]
branch = [
    #Multiplicity tests and interaction level
    {name = "containment_cut",       type = "both_particle"                               },
    {name = "primary_classification",type = "both_particle"                               },
    {name = "pid",                   type = "both_particle"                               },
    {name = "semantic_type",         type = "both_particle"                               },
]


[[tree]] # reco preselection
name = "particle_intfiducial_particlecontaintment_flashmatch_cut_reco"
sim_only = false
mode = "reco"
cut = [
    { name = "fiducial_cut",          type = "reco" },
    { name = "containment_cut",       type = "reco_particle" },
    { name = "valid_flashmatch",      type = "reco" },
    ]
branch = [
    #Multiplicity tests and interaction level
    {name = "containment_cut",       type = "both_particle"                               },
    {name = "primary_classification",type = "both_particle"                               },
    {name = "pid",                   type = "both_particle"                               },
    {name = "semantic_type",         type = "both_particle"                               },
]


[[tree]] # true preselection
name = "particle_intfiducial_particlecontainment_cut_true"
sim_only = false
mode = "reco"
cut = [
    { name = "fiducial_cut",          type = "true" },
    { name = "containment_cut",       type = "true_particle" },
    { name = "neutrino",              type = "true" },
    ]
branch = [
    #Multiplicity tests and interaction level
    {name = "containment_cut",       type = "both_particle"                               },
    {name = "primary_classification",type = "both_particle"                               },
    {name = "pid",                   type = "both_particle"                               },
    {name = "semantic_type",         type = "both_particle"                               },
    ]


[[tree]] # true preselection
name = "particle_intfiducial_intneutrino_cut_true"
sim_only = false
mode = "reco"
cut = [
    { name = "fiducial_cut",          type = "true" },
    { name = "neutrino",              type = "true" },
    ]
branch = [
    #Multiplicity tests and interaction level
    {name = "containment_cut",       type = "both_particle"                               },
    {name = "primary_classification",type = "both_particle"                               },
    {name = "pid",                   type = "both_particle"                               },
    {name = "semantic_type",         type = "both_particle"                               },
]

