[general]
output = "/exp/icarus/data/users/jkoh1/All_NuMI_BNB_2_shower_event_preselection_PID_confusion_matrix_threshold"
primfn = "default_primary_classification"
pidfn = "default_pid"
fsthresh = [
    "@photon_threshold",
    "@electron_threshold",
    "@muon_threshold",
    "@pion_threshold",
    "@proton_threshold",
]

[parameters]
photon_threshold = 25.0
electron_threshold = 25.0
muon_threshold = 143.425
pion_threshold = 25.0
proton_threshold = 50.0

#NuMI Samples

[[sample]]
name = "NuMI_simulation"
path = "/pnfs/icarus/persistent/users/dcarber/spine/combined_files/NuMI_CV_flat_cafs_2/*.root"
ismc = true
disable = false

#BNB samples

[[sample]]
name = "BNB_simulation"
path = "/pnfs/icarus/persistent/users/mueller/production/simulation/nominal/input*.flat.root"
ismc = true
disable = false

#pre-selection with PID cuts---------------------------------------------------------------------------------------

#reconstructed mode-----------------------------------------------------------------------------

[[tree]] # preselection
name = "particle_fiducial_flashmatch_containment_cut_reco"
sim_only = false
mode = "reco"
cut = [
    {name = "fiducial_cut",         type = "reco" },
    {name = "containment_cut",      type = "reco" },
    {name = "valid_flashmatch",    type = "reco" },
]
branch = [
    {name = "primary_classification", type = "both_particle"},
    {name = "pid", type = "both_particle"},
    {name = "semantic_type", type = "both_particle"},
    {name = "iou", type = "both_particle"},
    {name = "primary_softmax", type = "reco_particle"},
    {name = "secondary_softmax", type = "reco_particle"},
    {name = "photon_softmax", type = "reco_particle"},
    {name = "electron_softmax", type = "reco_particle"},
    {name = "muon_softmax", type = "reco_particle"},
    {name = "pion_softmax", type = "reco_particle"},
    {name = "proton_softmax", type = "reco_particle"},
    {name = "ke", type = "both_particle"},
    {name = "energy", type = "both_particle"},
    {name = "length", type = "both_particle"},
    {name = "csda_ke", type = "reco_particle"},
    {name = "mcs_ke", type = "reco_particle"},
    {name = "calo_ke", type = "reco_particle"},
]

#true mode-----------------------------------------------------------------------------

[[tree]] # preselection
name = "particle_fiducial_recoflashmatch_containment_cut_true"
sim_only = true
mode = "true"
cut = [
    {name = "fiducial_cut",         type = "true" },
    {name = "containment_cut",      type = "true" },
    {name = "valid_flashmatch",    type = "reco" },
]
branch = [
    {name = "primary_classification", type = "both_particle"},
    {name = "pid", type = "both_particle"},
    {name = "semantic_type", type = "both_particle"},
    {name = "iou", type = "both_particle"},
    {name = "primary_softmax", type = "reco_particle"},
    {name = "secondary_softmax", type = "reco_particle"},
    {name = "photon_softmax", type = "reco_particle"},
    {name = "electron_softmax", type = "reco_particle"},
    {name = "muon_softmax", type = "reco_particle"},
    {name = "pion_softmax", type = "reco_particle"},
    {name = "proton_softmax", type = "reco_particle"},
    {name = "ke", type = "both_particle"},
    {name = "energy", type = "both_particle"},
    {name = "length", type = "both_particle"},
    {name = "csda_ke", type = "reco_particle"},
    {name = "mcs_ke", type = "reco_particle"},
    {name = "calo_ke", type = "reco_particle"},

]