/**
     * @brief Binding for a 2 particle electron multiplicity cut.
     * @details This function binds the 2 particle multiplicity cut for
     * electrons, which corresponds to the index 1 in the
     * @ref utilities::count_primaries function.
     * @param obj the interaction to select on.
     * @param params the parameters for the cut. In this case, this sets the
     * kinetic energy threshold for an electron to count towards the
     * multiplicity. Defaults to 25 MeV.
     * @return true if the interaction has a single primary electron.
     */
    template<class T>
    bool two_electrons(const T & obj, std::vector<double> params={25.0,})
    {
        return particle_multiplicity(obj, 2, 1, params) == 2;
    }
    REGISTER_CUT_SCOPE(RegistrationScope::Both, two_electrons, two_electrons);

    /**
     * @brief Binding for a 2 particle photon multiplicity cut.
     * @details This function binds the 2 particle multiplicity cut for
     * electrons, which corresponds to the index 1 in the
     * @ref utilities::count_primaries function.
     * @param obj the interaction to select on.
     * @param params the parameters for the cut. In this case, this sets the
     * kinetic energy threshold for an electron to count towards the
     * multiplicity. Defaults to 25 MeV.
     * @return true if the interaction has a single primary electron.
     */
    template<class T>
    bool two_photons(const T & obj, std::vector<double> params={25.0,})
    {
        return particle_multiplicity(obj, 2, 0, params) == 2;
    }
    REGISTER_CUT_SCOPE(RegistrationScope::Both, two_photons, two_photons);
